// Müfredatın merkezi kavram kaydı. Her soru `concepts: [...]` ile buradaki id'lere bağlanır.
// core: true → doğrulama hattı "en az 5 tekrar, en az 2 farklı modül" kuralını raporlar (tekrar merdiveni).
// Bir modüle özel yeni kavram gerekiyorsa modules/NN-x/concepts.ts içine eklenir.
import { defineConcepts } from '@rm/content/define'

export default defineConcepts({
  // ---------- Araç zinciri ----------
  'tooling.platform': { title: 'Platformu kullanmak' },
  'tooling.node-runtime': { title: 'Node.js çalışma ortamı' },
  'tooling.pnpm': { title: 'pnpm ve paket yönetimi' },
  'tooling.package-json': { title: 'package.json', core: true },
  'tooling.semver': { title: 'Semantik sürümleme (^, ~)' },
  'tooling.lockfile': { title: 'Lockfile' },
  'tooling.scripts': { title: 'npm script’leri', core: true },
  'tooling.vite': { title: 'Vite geliştirme sunucusu', core: true },
  'tooling.vite-config': { title: 'vite.config.ts' },
  'tooling.hmr': { title: 'Hot Module Replacement' },
  'tooling.build': { title: 'Production build' },
  'tooling.tsconfig': { title: 'tsconfig.json', core: true },
  'tooling.type-check': { title: 'tsc ile tip kontrolü', core: true },
  'tooling.env': { title: 'Ortam değişkenleri (.env)', core: true },
  'tooling.git': { title: 'Git temel akışı' },
  'tooling.conventional-commits': { title: 'Conventional Commits' },
  'tooling.eslint': { title: 'ESLint', core: true },
  'tooling.eslint-config': { title: 'ESLint flat config' },
  'tooling.prettier': { title: 'Prettier' },
  'tooling.git-hooks': { title: 'husky + lint-staged' },
  'tooling.path-alias': { title: '@/ yol takma adı' },
  'tooling.ci': { title: 'CI (GitHub Actions)' },

  // ---------- JavaScript temelleri (tekrar) ----------
  'js.array-methods': { title: 'map / filter / reduce / find', core: true },
  'js.destructuring': { title: 'Destructuring', core: true },
  'js.spread': { title: 'Spread / rest', core: true },
  'js.optional-chaining': { title: 'Optional chaining ve ??', core: true },
  'js.async-await': { title: 'async / await ve Promise', core: true },
  'js.modules': { title: 'ES modülleri (import/export)' },
  'js.closures': { title: 'Closure' },
  'js.string-formatting': { title: 'Template literal ve biçimlendirme' },
  'js.dates': { title: 'Tarih işlemleri' },

  // ---------- Veri çekme ----------
  'fetch.basics': { title: 'fetch ile veri çekme', core: true },
  'fetch.headers-auth': { title: 'Authorization başlığı', core: true },
  'fetch.error-handling': { title: 'HTTP hatalarını yakalamak', core: true },
  'fetch.loading-states': { title: 'Yükleniyor / hata / başarı durumları', core: true },
  'fetch.query-params': { title: 'URLSearchParams ile query string' },
  'fetch.tmdb-images': { title: 'TMDB görsel URL’leri' },

  // ---------- TypeScript ----------
  'ts.primitives': { title: 'İlkel tipler' },
  'ts.inference': { title: 'Tip çıkarımı (inference)', core: true },
  'ts.object-types': { title: 'Nesne tipleri', core: true },
  'ts.arrays-tuples': { title: 'Diziler ve tuple' },
  'ts.type-vs-interface': { title: 'type ve interface' },
  'ts.union': { title: 'Union tipler', core: true },
  'ts.literal': { title: 'Literal tipler', core: true },
  'ts.narrowing': { title: 'Narrowing (daraltma)', core: true },
  'ts.functions': { title: 'Fonksiyon tipleri', core: true },
  'ts.optional-nullable': { title: 'Opsiyonel ve null olabilen alanlar', core: true },
  'ts.unknown-any': { title: 'unknown ve any' },
  'ts.generics': { title: 'Generics', core: true },
  'ts.generic-constraints': { title: 'Generic kısıtları (extends)' },
  'ts.partial': { title: 'Partial<T>', core: true },
  'ts.pick': { title: 'Pick<T, K>', core: true },
  'ts.omit': { title: 'Omit<T, K>', core: true },
  'ts.record': { title: 'Record<K, V>', core: true },
  'ts.readonly': { title: 'readonly ve Readonly<T>' },
  'ts.keyof-typeof': { title: 'keyof ve typeof', core: true },
  'ts.indexed-access': { title: 'İndeksli erişim tipleri (T["k"])' },
  'ts.discriminated-union': { title: 'Discriminated union', core: true },
  'ts.type-guards': { title: 'Type guard fonksiyonları', core: true },
  'ts.as-const': { title: 'as const' },
  'ts.satisfies': { title: 'satisfies' },
  'ts.async-types': { title: 'Promise ve async tipleri' },
  'ts.api-types': { title: 'API cevaplarını tiplemek', core: true },
  'ts.import-type': { title: 'import type' },
  'ts.return-parameters': { title: 'ReturnType / Parameters' },
  'ts.exhaustive-check': { title: 'never ile exhaustive kontrol' },

  // ---------- React temelleri ----------
  'react.jsx': { title: 'JSX' },
  'react.components': { title: 'Bileşenler', core: true },
  'react.props': { title: 'Props ve tipleri', core: true },
  'react.children': { title: 'children ve ReactNode' },
  'react.state': { title: 'useState', core: true },
  'react.state-snapshot': { title: 'State anlık görüntüsü (snapshot)' },
  'react.immutability': { title: 'Immutable güncelleme', core: true },
  'react.events': { title: 'Event’ler ve tipleri', core: true },
  'react.lists-keys': { title: 'Listeler ve key', core: true },
  'react.conditional-rendering': { title: 'Koşullu render', core: true },
  'react.controlled-input': { title: 'Controlled input', core: true },
  'react.lifting-state': { title: 'State’i yukarı taşımak' },
  'react.composition': { title: 'Composition', core: true },
  'react.render-cycle': { title: 'Render döngüsü' },
  'react.strict-mode': { title: 'StrictMode' },

  // ---------- Hook'lar ----------
  'react.useEffect': { title: 'useEffect', core: true },
  'react.useEffect.deps': { title: 'Dependency array', core: true },
  'react.useEffect.cleanup': { title: 'Effect cleanup', core: true },
  'react.race-conditions': { title: 'Race condition' },
  'react.abort-controller': { title: 'AbortController' },
  'react.derived-state': { title: 'Türetilmiş state (effect’e gerek yok)', core: true },
  'react.useRef': { title: 'useRef' },
  'react.useReducer': { title: 'useReducer' },
  'react.custom-hooks': { title: 'Custom hook’lar', core: true },
  'react.context': { title: 'Context', core: true },
  'react.useMemo': { title: 'useMemo' },
  'react.useCallback': { title: 'useCallback' },
  'react.useId': { title: 'useId' },
  'react.useEffectEvent': { title: 'useEffectEvent' },

  // ---------- Tailwind ----------
  'tailwind.utilities': { title: 'Utility-first CSS', core: true },
  'tailwind.layout': { title: 'Flex ve grid', core: true },
  'tailwind.responsive': { title: 'Responsive tasarım' },
  'tailwind.states': { title: 'hover / focus / disabled durumları' },
  'tailwind.dark-mode': { title: 'Dark mode' },
  'tailwind.theme': { title: '@theme ve tasarım token’ları' },
  'tailwind.cn': { title: 'cn() yardımcı fonksiyonu', core: true },
  'tailwind.cva': { title: 'cva ile variant’lar' },

  // ---------- React Router ----------
  'router.setup': { title: 'Router kurulumu', core: true },
  'router.nested-layouts': { title: 'Nested route ve layout' },
  'router.params': { title: 'URL parametreleri (useParams)', core: true },
  'router.search-params': { title: 'URL state (useSearchParams)', core: true },
  'router.navigation': { title: 'Link, NavLink, useNavigate' },
  'router.error-boundary': { title: 'errorElement ve 404' },
  'router.lazy': { title: 'Lazy route’lar' },
  'router.loaders': { title: 'Loader’lar' },
  'router.protected-routes': { title: 'Korumalı route’lar' },

  // ---------- Mimari ----------
  'arch.state-categories': { title: 'State kategorileri (server/client/URL/form)', core: true },
  'arch.feature-folders': { title: 'Feature bazlı klasör yapısı', core: true },
  'arch.api-client': { title: 'Tipli API client', core: true },
  'arch.api-error': { title: 'ApiError sınıfı' },
  'arch.separation-of-concerns': { title: 'UI ve mantığı ayırmak', core: true },
  'arch.component-api': { title: 'Component API tasarımı' },
  'arch.colocation': { title: 'Colocation' },
  'arch.barrel-files': { title: 'Barrel dosyalar' },
  'arch.refactoring': { title: 'Güvenli refactor' },
  'arch.adr': { title: 'Mimari karar kaydı (ADR)' },

  // ---------- Test ----------
  'test.vitest-basics': { title: 'Vitest: describe / it / expect', core: true },
  'test.aaa': { title: 'Arrange-Act-Assert' },
  'test.matchers': { title: 'Matcher’lar' },
  'test.mocks': { title: 'vi.fn / vi.mock / spy', core: true },
  'test.fake-timers': { title: 'Fake timer’lar' },
  'test.each': { title: 'it.each ile parametrik test' },
  'test.what-to-test': { title: 'Neyi test etmeli?' },
  'test.rtl-queries': { title: 'RTL sorgu önceliği (getByRole)', core: true },
  'test.user-event': { title: 'user-event', core: true },
  'test.async': { title: 'findBy / waitFor' },
  'test.custom-render': { title: 'Provider’lı custom render' },
  'test.render-hook': { title: 'renderHook' },
  'test.msw': { title: 'MSW ile API taklidi', core: true },
  'test.msw-overrides': { title: 'server.use ile test başına davranış' },
  'test.factories': { title: 'Test verisi fabrikaları' },
  'test.e2e': { title: 'Playwright E2E', core: true },
  'test.playwright-locators': { title: 'Playwright locator’ları' },
  'test.playwright-fixtures': { title: 'Fixture ve page object' },
  'test.playwright-network': { title: 'page.route ile ağ taklidi' },
  'test.playwright-auth': { title: 'storageState ile oturum' },

  // ---------- TanStack Query ----------
  'query.useQuery': { title: 'useQuery', core: true },
  'query.keys': { title: 'Query key’leri', core: true },
  'query.query-options': { title: 'queryOptions ve key factory', core: true },
  'query.stale-gc': { title: 'staleTime ve gcTime' },
  'query.dependent': { title: 'Bağımlı sorgular (enabled)' },
  'query.pagination': { title: 'Sayfalama (placeholderData)' },
  'query.infinite': { title: 'useInfiniteQuery' },
  'query.prefetch': { title: 'Prefetch' },
  'query.select': { title: 'select ile dönüştürme' },
  'query.useMutation': { title: 'useMutation', core: true },
  'query.invalidation': { title: 'Invalidation', core: true },
  'query.optimistic': { title: 'Optimistic update' },
  'query.suspense': { title: 'useSuspenseQuery' },
  'query.router': { title: 'Router loader entegrasyonu' },
  'query.testing': { title: 'Query hook’larını test etmek' },

  // ---------- Formlar ----------
  'form.rhf-register': { title: 'RHF register ve handleSubmit', core: true },
  'form.rhf-errors': { title: 'Form hataları', core: true },
  'form.rhf-controller': { title: 'Controller' },
  'form.rhf-field-array': { title: 'useFieldArray' },
  'form.rhf-form-state': { title: 'formState' },
  'form.rhf-reset': { title: 'reset ve defaultValues' },
  'form.a11y': { title: 'Erişilebilir formlar' },
  'form.react-actions': { title: 'React 19 form action’ları' },

  // ---------- Zod ----------
  'zod.schemas': { title: 'Zod şemaları', core: true },
  'zod.infer': { title: 'z.infer', core: true },
  'zod.refine': { title: 'refine / superRefine' },
  'zod.transform': { title: 'transform ve coerce' },
  'zod.resolver': { title: 'zodResolver', core: true },
  'zod.api-validation': { title: 'API cevabını doğrulamak' },
  'zod.env': { title: 'Tipli env' },
  'zod.schema-composition': { title: 'extend / pick / omit' },

  // ---------- Redux Toolkit ----------
  'redux.server-vs-client': { title: 'Server state ve client state', core: true },
  'redux.store': { title: 'configureStore', core: true },
  'redux.slice': { title: 'createSlice', core: true },
  'redux.typed-hooks': { title: 'Tipli hook’lar' },
  'redux.selectors': { title: 'Selector’lar ve createSelector' },
  'redux.listener': { title: 'Listener middleware' },
  'redux.async-thunk': { title: 'createAsyncThunk' },
  'redux.testing': { title: 'Slice ve store testleri' },

  // ---------- Kimlik doğrulama ----------
  'auth.jwt': { title: 'JWT ile giriş' },
  'auth.token-storage': { title: 'Token saklama' },
  'auth.refresh': { title: 'Refresh token' },
  'auth.protected-routes': { title: 'Korumalı sayfalar' },

  // ---------- Performans ve modern React ----------
  'perf.rerender': { title: 'Gereksiz render’lar', core: true },
  'perf.memo': { title: 'memo / useMemo / useCallback' },
  'perf.compiler': { title: 'React Compiler' },
  'perf.transitions': { title: 'useTransition / useDeferredValue' },
  'perf.code-splitting': { title: 'Code splitting' },
  'perf.virtualization': { title: 'Liste sanallaştırma' },
  'react.suspense': { title: 'Suspense' },
  'react.error-boundary': { title: 'Error boundary' },
  'react.actions': { title: 'Actions ve useActionState' },
  'react.useOptimistic': { title: 'useOptimistic' },
  'react.use': { title: 'use()' },

  // ---------- İleri pattern'ler ve a11y ----------
  'pattern.compound': { title: 'Compound components' },
  'pattern.slot': { title: 'asChild / Slot' },
  'pattern.headless': { title: 'Headless bileşenler' },
  'pattern.render-props-hoc': { title: 'Render props ve HOC' },
  'pattern.portal': { title: 'Portal' },
  'a11y.basics': { title: 'Erişilebilirlik temelleri', core: true },
  'a11y.keyboard': { title: 'Klavye ile kullanım' },
  'a11y.focus': { title: 'Focus yönetimi' },

  // ---------- shadcn/ui ----------
  'shadcn.setup': { title: 'shadcn/ui kurulumu' },
  'shadcn.components': { title: 'shadcn bileşenleri' },
  'shadcn.theming': { title: 'shadcn tema' },
})
