import { defineQuestion } from '@rm/content/define'

export default defineQuestion({
  type: 'project',
  title: 'Kitaplık’ı sıfırdan kur',
  difficulty: 'zor',
  concepts: [
    'capstone.project-setup',
    'tooling.package-json',
    'tooling.scripts',
    'tooling.vite-config',
    'tooling.tsconfig',
    'tooling.path-alias',
    'tooling.eslint-config',
    'tooling.prettier',
    'tailwind.utilities',
    'router.setup',
    'test.vitest-basics',
    'test.msw',
    'test.e2e',
  ],
  project: 'kitaplik',
  focusFiles: [
    'package.json',
    'vite.config.ts',
    'vitest.config.ts',
    'eslint.config.js',
    'playwright.config.ts',
    'src/app/routes.tsx',
    'src/app/providers.tsx',
    'src/main.tsx',
    'src/test/setup.ts',
  ],
  reviewFiles: [
    'package.json',
    '*.config.{ts,js}',
    'tsconfig*.json',
    'src/main.tsx',
    'src/app/**/*.tsx',
    'src/test/**/*.{ts,tsx}',
    'e2e/**/*.ts',
  ],
  rubric: [
    'Bağımlılıklar doğru grupta mı (tarayıcıya giden kod dependencies, araçlar devDependencies) ve sürümler kök catalog ile uyumlu mu?',
    'vite.config.ts yalnızca uygulamanın paketlenmesini, vitest.config.ts yalnızca test ortamını anlatıyor mu (mergeConfig ile)?',
    'ESLint config’i React kurallarını yalnızca src’ye, Node ortamını config dosyalarına uyguluyor mu; eslint-config-prettier en sonda mı?',
    'createRoutes ve AppProviders tek sorumluluklu mu; main.tsx ile testler aynı provider ağacını mı kullanıyor?',
    'Test setup dosyası her testten sonra DOM’u ve MSW handler’larını temizliyor, tanımsız isteği hata sayıyor mu?',
    'Playwright webServer ayarı CI’da taze sunucu açıyor (reuseExistingServer: !process.env.CI) ve tsconfig.node.json e2e dosyalarını da denetliyor mu?',
    'Şablondan kalan kullanılmayan dosyalar (örnek App.css, logolar, sayaç bileşeni) temizlenmiş mi?',
  ],
  hints: [
    'Yol haritasını sırayla izle ve her adımın sonunda ilgili komutu çalıştır (pnpm dev, pnpm typecheck, pnpm lint, pnpm test, pnpm test:e2e). Hata bir önceki adımda çıkarsa aramak kolay olur.',
    "“pnpm test e2e/smoke.spec.ts’i çalıştırıyor” hatası: vitest.config.ts’te exclude: [...configDefaults.exclude, 'e2e/**']. “@/ bulunamadı”: alias hem tsconfig.app.json paths’te hem vite.config.ts resolve.alias’ta olmalı.",
    'Duman testi için src/test/render.tsx’te bir renderApp(url) yaz: taze QueryClient (retry: false) → createMemoryRouter(createRoutes(queryClient), { initialEntries: [url] }) → <AppProviders queryClient={queryClient}><RouterProvider router={router} /></AppProviders>.',
  ],
  timeoutMs: 240000,
})
