import { defineQuestion } from '@rm/content/define'

export default defineQuestion({
  type: 'project',
  title: 'Kitaplık’ı sıfırdan kur',
  difficulty: 'zor',
  concepts: [
    'capstone.project-setup',
    'tooling.package-json',
    'tooling.scripts',
    'tooling.vite-config',
    'tooling.tsconfig',
    'tooling.path-alias',
    'tooling.eslint-config',
    'tooling.prettier',
    'tailwind.utilities',
    'router.setup',
    'test.vitest-basics',
    'test.msw',
    'test.e2e',
  ],
  project: 'kitaplik',
  focusFiles: [
    'package.json',
    'vite.config.ts',
    'vitest.config.ts',
    'eslint.config.js',
    'playwright.config.ts',
    'src/app/routes.tsx',
    'src/app/providers.tsx',
    'src/main.tsx',
    'src/test/setup.ts',
  ],
  reviewFiles: [
    'package.json',
    '*.config.{ts,js}',
    'tsconfig*.json',
    'src/main.tsx',
    'src/app/**/*.tsx',
    'src/test/**/*.{ts,tsx}',
    'e2e/**/*.ts',
  ],
  rubric: [
    'Bağımlılıklar doğru grupta mı (tarayıcıya giden kod dependencies, araçlar devDependencies) ve sürümler kök catalog ile uyumlu mu?',
    'vite.config.ts yalnızca uygulamanın paketlenmesini, vitest.config.ts yalnızca test ortamını anlatıyor mu (mergeConfig ile)?',
    'ESLint config’i React kurallarını yalnızca src’ye, Node ortamını config dosyalarına uyguluyor mu; eslint-config-prettier en sonda mı?',
    'createRoutes ve AppProviders tek sorumluluklu mu; main.tsx ile testler aynı provider ağacını mı kullanıyor?',
    'Test setup dosyası her testten sonra DOM’u ve MSW handler’larını temizliyor, tanımsız isteği hata sayıyor mu?',
    'Playwright webServer ayarı CI’da taze sunucu açıyor (reuseExistingServer: !process.env.CI) ve tsconfig.node.json e2e dosyalarını da denetliyor mu?',
    'Şablondan kalan kullanılmayan dosyalar (örnek App.css, logolar, sayaç bileşeni) temizlenmiş mi?',
  ],
  hints: [
    'Kurulumu parça parça ilerlet: paketler → typescript & vite → eslint & prettier → test altyapısı (vitest + playwright) → uygulama iskeleti.',
    'Vite ve Vitest konfigürasyonlarını ayır; Vitest içinde `e2e/**` dizinini hariç tut (`exclude`). `@/` alias ayarını hem `tsconfig.app.json` hem de `vite.config.ts` içinde tanımla.',
    'Uygulama sağlayıcıları ve rotaları için `createRoutes(queryClient)` ve `AppProviders({ queryClient, children })` export’larını hazırla; duman testinde `createMemoryRouter` ile aç.',
    'Şablondan gelen gereksiz dosyaları (`App.css`, `assets/react.svg`, sayaç state’i) temizlemeyi unutma. `vitest.config.ts`’te test ayarlarını doğrudan `vite.config.ts` içine gömme, ayrı dosyada tut.',
  ],
  timeoutMs: 240000,
})
